# Multiple Linear Regression in Statsmodels - Lab

## Introduction
In this lab, you'll practice fitting a multiple linear regression model on the Ames Housing dataset!

## Objectives
You will be able to:
* Determine if it is necessary to perform normalization/standardization for a specific model or set of data
* Use standardization/normalization on features of a dataset
* Identify if it is necessary to perform log transformations on a set of features
* Perform log transformations on different features of a dataset
* Use statsmodels to fit a multiple linear regression model
* Evaluate a linear regression model by using statistical performance metrics pertaining to overall model and specific parameters


## The Ames Housing Data

Using the specified continuous and categorical features, preprocess your data to prepare for modeling:
* Split off and one hot encode the categorical features of interest
* Log and scale the selected continuous features

In [1]:

import pandas as pd
import numpy as np

ames = pd.read_csv('ames.csv')

continuous = ['LotArea', '1stFlrSF', 'GrLivArea', 'SalePrice']
categoricals = ['BldgType', 'KitchenQual', 'SaleType', 'MSZoning', 'Street', 'Neighborhood']

## Continuous Features

In [2]:
# Log transform and normalize
ames_cont = ames[continuous]

# log features
log_names = [f'{column}_log' for column in ames_cont.columns]

ames_log = np.log(ames_cont)
ames_log.columns = log_names

# normalize (subract mean and divide by std)

def normalize(feature):
    return (feature - feature.mean()) / feature.std()

ames_log_norm = ames_log.apply(normalize)

## Categorical Features

In [3]:
ames_ohe = pd.get_dummies(ames[categoricals], prefix=categoricals, drop_first=True)

## Combine Categorical and Continuous Features

In [4]:
preprocessed = pd.concat([ames_log_norm, ames_ohe], axis=1)
preprocessed.head()

LotArea_log  1stFlrSF_log  GrLivArea_log  SalePrice_log  BldgType_2fmCon  \
0    -0.133185     -0.803295       0.529078       0.559876                0   
1     0.113403      0.418442      -0.381715       0.212692                0   
2     0.419917     -0.576363       0.659449       0.733795                0   
3     0.103311     -0.439137       0.541326      -0.437232                0   
4     0.878108      0.112229       1.281751       1.014303                0   

   BldgType_Duplex  BldgType_Twnhs  BldgType_TwnhsE  KitchenQual_Fa  \
0                0               0                0               0   
1                0               0                0               0   
2                0               0                0               0   
3                0               0                0               0   
4                0               0                0               0   

   KitchenQual_Gd  ...  Neighborhood_NoRidge  Neighborhood_NridgHt  \
0               1  ...                     0                     0   
1               0  ...                     0                     0   
2               1  ...                     0                     0   
3               1  ...                     0                     0   
4               1  ...                     1                     0   

   Neighborhood_OldTown  Neighborhood_SWISU  Neighborhood_Sawyer  \
0                     0                   0                    0   
1                     0                   0                    0   
2                     0                   0                    0   
3                     0                   0                    0   
4                     0                   0                    0   

   Neighborhood_SawyerW  Neighborhood_Somerst  Neighborhood_StoneBr  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   Neighborhood_Timber  Neighborhood_Veenker  
0                    0                     0  
1                    0                     1  
2                    0                     0  
3                    0                     0  
4                    0                     0  

[5 rows x 48 columns]

## Run a linear model with SalePrice as the target variable in statsmodels

In [5]:
X = preprocessed.drop('SalePrice_log', axis=1)
y = preprocessed['SalePrice_log']

In [6]:
import statsmodels.api as sm
X_int = sm.add_constant(X)
model = sm.OLS(y,X_int).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:          SalePrice_log   R-squared:                       0.839
Model:                            OLS   Adj. R-squared:                  0.834
Method:                 Least Squares   F-statistic:                     156.5
Date:                Mon, 09 May 2022   Prob (F-statistic):               0.00
Time:                        18:06:44   Log-Likelihood:                -738.14
No. Observations:                1460   AIC:                             1572.
Df Residuals:                    1412   BIC:                             1826.
Df Model:                          47                                         
Covariance Type:            nonrobust                                         
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   -0.1317      0.263     -0.500      0.617      -0.648       0.385
LotArea_log              0.1033      0.019      5.475      0.000       0.066       0.140
1stFlrSF_log             0.1371      0.016      8.584      0.000       0.106       0.168
GrLivArea_log            0.3768      0.016     24.114      0.000       0.346       0.407
BldgType_2fmCon         -0.1715      0.079     -2.173      0.030      -0.326      -0.017
BldgType_Duplex         -0.4203      0.062     -6.813      0.000      -0.541      -0.299
BldgType_Twnhs          -0.1403      0.093     -1.513      0.130      -0.322       0.042
BldgType_TwnhsE         -0.0512      0.060     -0.858      0.391      -0.168       0.066
KitchenQual_Fa          -0.9999      0.088    -11.315      0.000      -1.173      -0.827
KitchenQual_Gd          -0.3820      0.050     -7.613      0.000      -0.480      -0.284
KitchenQual_TA          -0.6692      0.055    -12.111      0.000      -0.778      -0.561
SaleType_CWD             0.2285      0.215      1.061      0.289      -0.194       0.651
SaleType_Con             0.5861      0.304      1.927      0.054      -0.010       1.183
SaleType_ConLD           0.3151      0.155      2.029      0.043       0.010       0.620
SaleType_ConLI           0.0331      0.195      0.169      0.865      -0.350       0.416
SaleType_ConLw           0.0161      0.196      0.082      0.935      -0.368       0.400
SaleType_New             0.2999      0.079      3.803      0.000       0.145       0.455
SaleType_Oth             0.1178      0.245      0.480      0.631      -0.364       0.599
SaleType_WD              0.1748      0.065      2.676      0.008       0.047       0.303
MSZoning_FV              1.0666      0.193      5.526      0.000       0.688       1.445
MSZoning_RH              0.8768      0.194      4.512      0.000       0.496       1.258
MSZoning_RL              0.9961      0.162      6.151      0.000       0.678       1.314
MSZoning_RM              1.1023      0.152      7.264      0.000       0.805       1.400
Street_Pave             -0.2131      0.180     -1.182      0.237      -0.567       0.141
Neighborhood_Blueste     0.0529      0.318      0.167      0.868      -0.571       0.677
Neighborhood_BrDale     -0.4627      0.171     -2.711      0.007      -0.798      -0.128
Neighborhood_BrkSide    -0.6498      0.137     -4.735      0.000      -0.919      -0.381
Neighborhood_ClearCr    -0.2102      0.144     -1.456      0.146      -0.493       0.073
Neighborhood_CollgCr    -0.0761      0.119     -0.641      0.522      -0.309       0.157
Neighborhood_Crawfor    -0.0823      0.129     -0.638      0.523      -0.335       0.171
Neighborhood_Edwards    -0.7613      0.124     -6.143      0.000      -1.004      -0.518
Neighborhood_Gilbert    -0.0980      0.126     -0.777    

## Run the same model in scikit-learn

In [7]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X, y)

LinearRegression()

In [8]:
# coefficients
linreg.coef_

array([ 0.10327192,  0.1371289 ,  0.37682133, -0.1714623 , -0.42033885,
       -0.14034113, -0.05120194, -0.99986001, -0.38202198, -0.66924909,
        0.22847737,  0.5860786 ,  0.31510567,  0.0330941 ,  0.01608664,
        0.29985338,  0.11784232,  0.17480326,  1.06663561,  0.87681007,
        0.99609131,  1.10228499, -0.21311107,  0.05293276, -0.46271253,
       -0.64982261, -0.21019239, -0.07609253, -0.08233633, -0.76126683,
       -0.09799942, -0.96183328, -0.69182575, -0.2553217 , -0.44067351,
       -0.01595046, -0.26762962,  0.36313165,  0.36259667, -0.93504972,
       -0.69976325, -0.47543141, -0.23309732,  0.09502969,  0.42957077,
        0.0056924 ,  0.12762613])

In [9]:
# intercept
linreg.intercept_

-0.13169736916670177

## Predict the house price given the following characteristics (before manipulation!!)

Make sure to transform your variables as needed!

- LotArea: 14977
- 1stFlrSF: 1976
- GrLivArea: 1976
- BldgType: 1Fam
- KitchenQual: Gd
- SaleType: New
- MSZoning: RL
- Street: Pave
- Neighborhood: NridgHt

In [10]:
# getting the used column names for the df

continuous.remove("SalePrice")

used_cols = [*continuous, *categoricals]
used_cols

['LotArea',
 '1stFlrSF',
 'GrLivArea',
 'BldgType',
 'KitchenQual',
 'SaleType',
 'MSZoning',
 'Street',
 'Neighborhood']

In [11]:
# creating an empty dataframe for the new row
new_row = pd.DataFrame(columns=used_cols)

In [12]:
# adding the details provided into the empty dataframe
new_row = new_row.append({"LotArea": 14977,
                          '1stFlrSF': 1976,
                          'GrLivArea': 1976,
                          'BldgType': '1Fam',
                          'KitchenQual': 'Gd',
                          'SaleType': 'New',
                          'MSZoning': 'RL',
                          'Street': 'Pave',
                          'Neighborhood': 'NridgHt'},
                          ignore_index=True)
new_row

LotArea 1stFlrSF GrLivArea BldgType KitchenQual SaleType MSZoning Street  \
0   14977     1976      1976     1Fam          Gd      New       RL   Pave   

  Neighborhood  
0      NridgHt

In [13]:
# first we'll tackle the continuous columns
new_row_cont = new_row[continuous]

# log features
log_names = [f'{column}_log' for column in new_row_cont.columns]

new_row_log = np.log(new_row_cont.astype(float)) # won't work unless float
new_row_log.columns = log_names

# normalizing
for col in continuous:
    # normalize using mean and std from overall dataset
    new_row_log[f'{col}_log'] = (new_row_log[f'{col}_log'] - ames[col].mean()) / ames[col].std()
new_row_log

LotArea_log  1stFlrSF_log  GrLivArea_log
0    -1.052694     -2.987777      -2.869517

In [14]:
# now time for the categoricals
new_row_cat = new_row[categoricals]

new_row_ohe = pd.DataFrame(columns = ames_ohe.columns)

# using complicated for loops to ohe the new row
ohe_dict = {}
for col_type in new_row_cat.columns:
    col_list = [c for c in new_row_ohe.columns.to_list() if col_type in c]
    for x in col_list:
        if new_row_cat[col_type][0] in x:
            ohe_dict[x] = 1
        else:
            ohe_dict[x] = 0
            
# putting the results in a dataframe
new_row_ohe = new_row_ohe.append(ohe_dict, ignore_index=True)
new_row_ohe

BldgType_2fmCon BldgType_Duplex BldgType_Twnhs BldgType_TwnhsE  \
0               0               0              0               0   

  KitchenQual_Fa KitchenQual_Gd KitchenQual_TA SaleType_CWD SaleType_Con  \
0              0              1              0            0            0   

  SaleType_ConLD  ... Neighborhood_NoRidge Neighborhood_NridgHt  \
0              0  ...                    0                    1   

  Neighborhood_OldTown Neighborhood_SWISU Neighborhood_Sawyer  \
0                    0                  0                   0   

  Neighborhood_SawyerW Neighborhood_Somerst Neighborhood_StoneBr  \
0                    0                    0                    0   

  Neighborhood_Timber Neighborhood_Veenker  
0                   0                    0  

[1 rows x 44 columns]

In [15]:
# putting together this row's data - both continuous and categorical
new_row_processed = pd.concat([new_row_log, new_row_ohe], axis=1)
new_row_processed

LotArea_log  1stFlrSF_log  GrLivArea_log BldgType_2fmCon BldgType_Duplex  \
0    -1.052694     -2.987777      -2.869517               0               0   

  BldgType_Twnhs BldgType_TwnhsE KitchenQual_Fa KitchenQual_Gd KitchenQual_TA  \
0              0               0              0              1              0   

   ... Neighborhood_NoRidge Neighborhood_NridgHt Neighborhood_OldTown  \
0  ...                    0                    1                    0   

  Neighborhood_SWISU Neighborhood_Sawyer Neighborhood_SawyerW  \
0                  0                   0                    0   

  Neighborhood_Somerst Neighborhood_StoneBr Neighborhood_Timber  \
0                    0                    0                   0   

  Neighborhood_Veenker  
0                    0  

[1 rows x 47 columns]

In [16]:
# now - FINALLY - we can model

new_row_pred_log = linreg.predict(new_row_processed)
new_row_pred_log

array([-0.66800851])

In [17]:
# prediction needs to be scaled and exponentiated
np.exp(new_row_pred_log) * ames["SalePrice"].std() + ames["SalePrice"].mean()

array([221653.64351813])

## Summary
Congratulations! You pre-processed the Ames Housing data using scaling and standardization. You also fitted your first multiple linear regression model on the Ames Housing data using statsmodels and scikit-learn!